ECommerce-master/Models/ErrorViewModel.cs
using System;

namespace ECommerce.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerce-master/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Model;
using ECommerce.Model.Interfaces;
using ECommerce.Model.Interfaces.Services;
using Microsoft.AspNetCore.Authorization;

namespace ECommerce.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {
        
        private readonly IProdutoService _produtoService;
        private readonly ICompraService _compraService;

      
        public CompraController(IProdutoService produtoService,ICompraService compraService)
        {
            _produtoService = produtoService;
            _compraService = compraService;
        }

        // GET: Compra
        public async Task<IActionResult> Index()
        {
            
            var historicoTotal = await _compraService.GetAll();
            return View(historicoTotal);
        }

        // GET: Compra/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var compra = await _compraService.GetDetails(id);
            return View(compra);
        }

        // GET: Compra/Create

        [HttpGet]
        public async Task<IActionResult> Create(int produtoId)
        {
            
            var produto = await _produtoService.GetDetails(produtoId);
            var compraModel = new CompraModel
            {
                ProdutoNome = produto.Nome,
                ProdutoId = produto.Id,
                Preço = produto.Preco,
                ProdutoImagem = produto.UriBlob,
                
            };

            return View(compraModel);
        }

        // POST: Compra/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProdutoId,ProdutoNome,ProdutoImagem,Preço,Comprador,FormaDePagamento")] CompraModel compraModel)
        {
            if (ModelState.IsValid)
            {
                var usuario = User.Identity.Name;
                compraModel.Comprador = usuario;
                await _compraService.Create(compraModel); 
                return RedirectToAction("Index", "Produto");
            }
            return View(compraModel);
        }
        
        public async Task<IActionResult> UserCompras(string usuario)
        {
            
            var historico = await _compraService.GetCompraByUser(usuario);
            return View(historico);
        }
    }
}

ECommerce-master/Controllers/HomeController.cs
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerce-master/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ECommerce.Model;
using Microsoft.AspNetCore.Authorization;
using ECommerce.Model.Interfaces;

using ECommerce.Model.Interfaces.UnitOfWork;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace ECommerce.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        private readonly IProdutoService _produtoServices;
        private readonly IUnitOfWork _unitOfWork;
        public ProdutoController(IProdutoService produtoService, IUnitOfWork unitOfWork)
        {
            _produtoServices = produtoService;
            _unitOfWork = unitOfWork;
        } 
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            
            var catalogo = _produtoServices.GetAll();
           
            return  View(await catalogo);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Nome,Categoria,UriBlob,Preco,Vendedor")] ProdutoModel produto,IFormFile formFile )
        {
            if (ModelState.IsValid)
            {
                produto.Vendedor = User.Identity.Name;
                string imageBase64;
                using (var ms = new MemoryStream())
                {
                    formFile.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    imageBase64 = Convert.ToBase64String(fileBytes);
                }
                produto.UriBlob= imageBase64;
                await _produtoServices.Create(produto);
               
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
            
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var produto = await _produtoServices.GetDetails(id);
            if(produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id,Nome,Categoria,Preco,Vendedor")] ProdutoModel produto,IFormFile formFile)
        {
            if (ModelState.IsValid)
            {
                string imageBase64;
                using (var ms = new MemoryStream())
                {
                    formFile.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    imageBase64 = Convert.ToBase64String(fileBytes);
                }
                produto.UriBlob = imageBase64;
                await _produtoServices.Update(produto);
               
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<ActionResult> Delete(int id)
        {
            var produto = await _produtoServices.GetDetails(id);
            var uri = produto.UriBlob;
            await _produtoServices.Delete(id,uri);
            
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var produto = await _produtoServices.GetDetails(id);

            return View(produto);
        }
    }
}

ECommerce-master/Views/Compra/Create.cshtml
@model ECommerce.Model.CompraModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CompraModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProdutoId" class="control-label"></label>
                <label asp-for="ProdutoId" class="form-control" >@Model.ProdutoId</label>
                <input asp-for="ProdutoId" hidden />
                <span asp-validation-for="ProdutoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProdutoNome" class="control-label"></label>
                <label asp-for="ProdutoNome" class="form-control">@Model.ProdutoNome</label>
                <input asp-for="ProdutoNome" hidden />
                <span asp-validation-for="ProdutoNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProdutoImagem" class="control-label"></label>
                <label asp-for="ProdutoImagem" class="form-control">@Model.ProdutoImagem</label>
                <input asp-for="ProdutoImagem" hidden />
                <span asp-validation-for="ProdutoImagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preço" class="control-label"></label>
                <label asp-for="Preço" class="form-control">@Model.Preço</label>
                <input asp-for="Preço" hidden />
                <span asp-validation-for="Preço" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormaDePagamento" class="control-label"></label>
                <input asp-for="FormaDePagamento" class="form-control" />
                <span asp-validation-for="FormaDePagamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller = "Produto"asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerce-master/Views/Compra/Delete.cshtml
@model ECommerce.Model.CompraModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompraModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoImagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoImagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preço)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preço)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comprador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comprador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FormaDePagamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FormaDePagamento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ECommerce-master/Views/Compra/Details.cshtml
@model ECommerce.Model.CompraModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CompraModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoNome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoNome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoImagem)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Html.DisplayFor(modelItem => modelItem.ProdutoImagem)" width="100" height="100" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preço)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preço)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comprador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comprador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FormaDePagamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FormaDePagamento)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ECommerce-master/Views/Compra/Index.cshtml
@model IEnumerable<ECommerce.Model.CompraModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProdutoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProdutoNome)
            </th>
            <th>
               <a @Html.DisplayNameFor(model => model.ProdutoImagem)> Imagem </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preço)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comprador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FormaDePagamento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoNome)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.ProdutoImagem)" width="100" height="100" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preço)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comprador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FormaDePagamento)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ECommerce-master/Views/Compra/UserCompras.cshtml
@model IEnumerable<ECommerce.Model.CompraModel>

@{
    ViewData["Title"] = "UserCompras";
}

<h1>Historico de Compras</h1>


<table class="table">
    <thead>
        <tr>
            <th>
               <a @Html.DisplayNameFor(model => model.ProdutoId)>Id</a>
            </th>
            <th>
               <a @Html.DisplayNameFor(model => model.ProdutoNome)>Nome</a>
            </th>
            <th>
                <a @Html.DisplayNameFor(model => model.ProdutoImagem)>Imagem </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preço)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comprador)
            </th>
            <th>
               <a @Html.DisplayNameFor(model => model.FormaDePagamento)>Forma de Pagamento</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoNome)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.ProdutoImagem)" width="100" height="100" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preço)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comprador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FormaDePagamento)
            </td>
            <td>
                <a asp-action="Details" asp-controller="Produto" asp-route-id="@item.ProdutoId">Details</a> | 
            </td>
        </tr>
}
    </tbody>
</table>

ECommerce-master/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerce-master/Views/Produto/Create.cshtml
@model ECommerce.Model.ProdutoModel

@{
    ViewData["Title"] = "Create";
}

<h1>Formulário de adição ao Catálogo</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Imagem</label>
                <input  type="file" id="formFile" name="formFile" class="custom-input" >
               
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco"  class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>            
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerce-master/Views/Produto/Delete.cshtml
@model ECommerce.Model.ProdutoModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProdutoModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UriBlob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UriBlob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vendedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vendedor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ECommerce-master/Views/Produto/Details.cshtml
@model ECommerce.Model.ProdutoModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProdutoModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class="col-sm-2">
            <a @Html.DisplayNameFor(model => model.UriBlob)>Imagem</a>
        </dt>
        <dd class="col-sm-10">
            <img src="@Html.DisplayFor(modelItem => modelItem.UriBlob)" width="100" height="100" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vendedor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vendedor)
        </dd>
    </dl>
    </div>

<div>
    <a asp-controller="Compra" asp-action="Create" asp-route-produtoId="@Model.Id">Ir para Compra</a>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
    <a asp-action="Index">Back to List</a>
</div>

ECommerce-master/Views/Produto/Edit.cshtml
@model ECommerce.Model.ProdutoModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ProdutoModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit"  enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label"></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Imagem</label>
                <input type="file" id="formFile" name="formFile" class="custom-input">
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vendedor" class="control-label"></label>
                <input asp-for="Vendedor" class="form-control" />
                <span asp-validation-for="Vendedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ECommerce-master/Views/Produto/Index.cshtml
@model IEnumerable<ECommerce.Model.ProdutoModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Catálogo</h1>

<p>
    <a asp-action="Create">Adicionar Produto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Categoria)
            </th>
            <th>
                <a @Html.DisplayNameFor(model => model.UriBlob) class="custom-file"> Imagem</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vendedor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
               <img src="@Html.DisplayFor(modelItem => item.UriBlob)" width="100" height="100"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco) 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendedor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar Produto</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes do Produto</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Remover do Catálogo</a>
            </td>
        </tr>
}
    </tbody>
</table>

ECommerce-master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Catalogo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="UserCompras" asp-route-usuario="@User.Identity.Name">Suas Compras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>